DSchool/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = 'Driving School Administration'
admin.site.site_title = 'Driving School Administration'
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Student.urls')),
    path('instructor/', include('Instructor.urls')),
    path('secretary/', include('Secretary.urls')),  
    path('logout/', LogoutView.as_view(), name='logout'),
]

Instructor/urls.py
from django.urls import path
from . import views

app_name = 'Instructor'
urlpatterns =[
	path('homeInstructor/',views.homeInstructor, name='homeInstructor'),
    path('', views.loginInstructor, name='loginInstructor'),
    path('profileStudent/<int:student_id>/', views.profileStudent, name='studentProfile'),
    path('detailInstructor', views.detailInstructor, name='detailInstructor'),
    path('addPlanningInstructor/', views.addPlanningInstructor, name='addPlanningInstructor'),

    path('supprimer_planning/<int:planning_id>/', views.supprimer_planning, name='supprimer_planning'),
    path('confirmation_suppression/<int:planning_id>/', views.confirmer_suppression, name='confirmer_suppression'),
    path('instructor/planning/<int:planning_id>/modifier/', views.modifier_entry, name='modifier_entry'),
]

Secretary/urls.py
from django.urls import path
from . import views

app_name = 'Secretary'
urlpatterns =[
	path('',views.homeSecretary, name='homeSecretary'),
    path("student/<int:pk>/acount", views.studentDetail, name="studentDetail"),
    path('student/<int:pk>/planning', views.planningStudent, name='planningStudent'),
    path('studentList/', views.studentList, name='studentList'), 
    path('student/addStudent', views.addStudent, name='addStudent'),
    path('student/<int:pk>/delete', views.deleteStudent, name='deleteStudent'),
    path('confirmStudent/<int:pk>/to-delete', views.confirmDeleteStudent, name='confirmDeleteStudent'),
    path('student/<int:pk>/edit', views.editStudent, name='editStudent'),
    path('student/<int:pk>/addPlanning', views.addPlanning, name='addPlanning'),
    path('instructor/<int:pk>/account', views.instructorDetail, name='instructorDetail'),
    path('instructorList/', views.instructorList, name='instructorList'),
    path('instructor/<int:pk>/planning', views.planningInstructor, name='planningInstructor'),
    path('instructor/addInstructor', views.addInstructor, name='addInstructor'),
    path('instructor/<int:pk>/addPlanning', views.addPlanningIns, name='addPlanningIns'),
    path('instructor/<int:pk>/delete', views.deleteInstructor, name='deleteInstructor'),
    path('confirmInsctructor/<int:pk>/to-delete', views.confirmDeleteInstructor, name='confirmDeleteInstructor'),
    path('instructor/<int:pk>/edit', views.editInstructor, name='editInstructor'),
    path('secretary/planning/<int:planning_id>/modifier/', views.modifierPlanning, name='modifierPlanning'),
    path('confirmDeletePanning/<int:planning_id>/', views.confirmDeletePlanning, name='confirmDeletePlanning'),
    path('supprimerPlanning/<int:planning_id>/', views.supprimerPlanning, name='supprimerPlanning'),
    path('addPlanningGeneral/', views.addPlanningGeneral, name='addPlanningGeneral'),
]

Secretary/templates/addPlanning.html
{% extends "base.html" %}
{% block title %}Add{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">

        <div class="col-6">

            <div class="custom-form mx-auto">
                <h2>Ajouter un rdv pour {{ student.username }}</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group ">
                        {{ form.instructor.label_tag }}
                        {{ form.instructor }}
                    </div>
                    <div class="form-group ">
                        {{ form.date.label_tag }}
                        <input type="datetime-local" name="{{ form.date.name }}" value="{{ form.date.value|default:'' }}" required>
                    </div>
                    <div class="form-group ">
                        {{ form.place.label_tag }}
                        {{ form.place }}
                    </div>


                    <button type="submit" class="btn btn-dark">Enregistrer</button>
                    <a class="btn btn-dark" href="{% url 'Secretary:planningStudent' student.id%}">Retour</a>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Secretary/templates/addPlanningGeneral.html
{% extends "base.html" %}
{% block title %}Add{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">

        <div class="col-6">

            <div class="custom-form mx-auto">
                <h2>Ajouter un rdv</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group ">
                        {{ form.student.label_tag }}
                        {{ form.student }}
                    </div>
                    <div class="form-group ">
                        {{ form.instructor.label_tag }}
                        {{ form.instructor }}
                    </div>
                    <div class="form-group ">
                        {{ form.date.label_tag }}
                        <input type="datetime-local" name="{{ form.date.name }}"
                            value="{{ form.date.value|default:'' }}" required>
                    </div>
                    <div class="form-group ">
                        {{ form.place.label_tag }}
                        {{ form.place }}
                    </div>


                    <button type="submit" class="btn btn-dark">Enregistrer</button>
                    <a class="btn btn-dark" href="{% url 'Secretary:homeSecretary' %}">Retour</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Secretary/templates/addPlanningIns.html
{% extends "base.html" %}
{% block title %}Add{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">

        <div class="col-6">

            <div class="custom-form mx-auto">
                <h2>Ajouter un rdv pour {{ instructor.username }}</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group ">
                        {{ form.student.label_tag }}
                        {{ form.student }}
                    </div>
                    <div class="form-group ">
                        {{ form.date.label_tag }}
                        <input type="datetime-local" name="{{ form.date.name }}"
                            value="{{ form.date.value|default:'' }}" required>
                    </div>
                    <div class="form-group ">
                        {{ form.place.label_tag }}
                        {{ form.place }}
                    </div>


                    <button type="submit" class="btn btn-dark">Enregistrer</button>
                    <a class="btn btn-dark" href="{% url 'Secretary:planningInstructor' instructor.id%}">Retour</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Secretary/templates/confirmDeleteInstructor.html
{% extends "base.html" %}
{% block title %}Confirm{% endblock %}
{% block content %}
<div class="container-fluid mt-5">
    <div class="row justify-content-center">
        <div class="col-4">

            <h1> Êtes-vous sûr de vouloir supprimer l'instructeur {{ instructor.username }} ?</h1>
            <a class="btn btn-danger" href="{% url 'Secretary:deleteInstructor' instructor.id %}">Confirmer la suppression</a>
            <a class="btn btn-secondary" href="{% url 'Secretary:instructorList' %}">Annuler</a>
        </div>
    </div>
</div>
{% endblock %}

Secretary/templates/confirmDeletePlanning.html
{% extends "base.html" %}
{% block title %}Confirm{% endblock %}
{% block content %}
<div>
    <form method="post" action="{% url 'Secretary:supprimerPlanning' planning.id %}">
        {% csrf_token %}
        <p>Êtes-vous sûr de vouloir supprimer le RDV entre {{ planning.student }} et {{ planning.instructor }} le {{ planning.date|date:"d-m-Y" }} à
            {{ planning.date|date:"H:i" }} ?</p>
        <input class="btn btn-danger" type="submit" value="Confirmer la suppression">
    </form>
    <a class="btn btn-dark" href="{% url 'Secretary:homeSecretary' %}">Retour au planning</a>
</div>
{% endblock %}

Secretary/templates/confirmDeleteStudent.html
{% extends "base.html" %}
{% block title %}Confirm{% endblock %}
{% block content %}
<div class="container-fluid mt-5">
    <div class="row justify-content-center">
        <div class="col-4">

            <h1> Êtes-vous sûr de vouloir supprimer l'étudiant {{ student.username }} ?</h1>
            <a class="btn btn-danger" href="{% url 'Secretary:deleteStudent' student.id %}">Confirmer la suppression</a>
            <a class="btn btn-secondary" href="{% url 'Secretary:studentList' %}">Annuler</a>
        </div>
    </div>
</div>
{% endblock %}

Secretary/templates/editInstructor.html
{% extends "base.html" %}
{% block title %}Edit{% endblock %}
{% block content %}
<div class="container">
    <div class="row">

        <div class="custom-form mx-auto">
            <h2 class="text-center mb-4">Instructor Form</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-group ">
                    {{ form.username.label_tag }}
                    {{ form.username }}
                </div>
                <div class="form-group ">
                    {{ form.password.label_tag }}
                    {{ form.password }}
                </div>
                <div class="form-group ">
                    {{ form.name.label_tag }}
                    {{ form.name }}
                </div>
                <div class="form-group ">
                    {{ form.lastname.label_tag }}
                    {{ form.lastname }}
                </div>
                <button type="submit" class="btn btn-dark">Valider</button>
                <a class="btn btn-dark" href="{% url 'Secretary:instructorList'%}">Retour</a>

            </form>
        </div>
    </div>
</div>
{% endblock %}

Secretary/templates/editStudent.html
{% extends "base.html" %}
{% block title %}Edit{% endblock %}
{% block content %}
<div class="container">
    <div class="row">

        <div class="custom-form mx-auto">
            <h2 class="text-center mb-4">Student Form</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-group ">
                    {{ form.username.label_tag }}
                    {{ form.username }}
                </div>
                <div class="form-group ">
                    {{ form.password.label_tag }}
                    {{ form.password }}
                </div>
                <div class="form-group ">
                    {{ form.h_total.label_tag }}
                    {{ form.h_total }}
                </div>
                <div class="form-group ">
                    {{ form.h_remaining.label_tag }}
                    {{ form.h_remaining }}
                </div>
                <button type="submit" class="btn btn-dark">Valider</button>
                <a class="btn btn-dark" href="{% url 'Secretary:studentList'%}">Retour</a>

            </form>
        </div>
    </div>
</div>
{% endblock %}

Secretary/templates/instructorDetail.html
{% extends "base.html" %}
{% block title %}Profil{% endblock %}
{% block content %}

<div class="container-fluid">

    <div class="row justify-content-center mt-5">
        <div class="col-8">


            <h1>Détails de l'instructeur : {{ instructor.username }}</h1>
            <a class="btn btn-dark" href="{% url 'Secretary:homeSecretary'%}">Retour</a>

            <table class="table table-bordered table-striped table-hover mt-3">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Nom d'utilisateur</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Voir son planning</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ instructor.username }}</td>
                        <td>{{ instructor.name }}</td>
                        <td>{{ instructor.lastname }}</td>
                        <td><a class="btn btn-dark" href="{% url 'Secretary:planningInstructor' instructor.id %}">Voir son planning</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

Secretary/templates/instructorList.html
{% extends "base.html" %}
{% block title %}instructor{% endblock %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
</ul>
{% endif %}
<div class="row justify-content-center mt-5">
    <div class="col-10">
        <h1>Driving School</h1>
        <h2>instructors</h2>
        <a class="btn btn-primary" href="{% url 'Secretary:homeSecretary' %}">Back</a>
        <a class="btn btn-dark" href="{% url 'Secretary:addInstructor' %}">Add an instructor</a>
        {% if instructor_list%}
        <table class="table table-bordered table-striped table-hover mt-4">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Nom d'utilisateur</th>
                    <th scope="col">Planning</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for instructor in instructor_list%}
                <tr>

                    <td><a class="btn btn-link" href="{% url 'Secretary:instructorDetail' instructor.id %}">{{ instructor.username }}</a></td>
                    {% if instructor.planning_set.all %}
                    <td><a class="btn btn-dark" href="{% url 'Secretary:planningInstructor' instructor.id %}">Voir le
                            planning</a>
                    </td>
                    {% else %}
                    <td>
                        <a href="{% url 'Secretary:addPlanningIns' instructor.id %}" class="btn btn-info">Ajouter un RDV</a>
                    </td>
                    {% endif %}
                    <td class="d-flex">
                        <a class="btn btn-danger"
                            href="{% url 'Secretary:confirmDeleteInstructor' instructor.id %}">Supprimer</a>

                        <a href="{% url 'Secretary:editInstructor' instructor.id %}" class="btn btn-warning ml-2">Modifier</a>

                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

Secretary/templates/modifierPlanning.html
{% extends "base.html" %}
{% block title %}Modifier{% endblock %}
{% block content %}
<div>
    <form method="post">
        {% if error_message %}<p>{{ error_message }}</p>{% endif %}
        {% csrf_token %}
        {{ form.student }}
        {{ form.instructor }}
        {{ form.date }}
        {{ form.place }}
        <input class="btn btn-primary" type="submit" value="Enregistrer les modifications">
    </form>
    <a class="btn btn-dark" href="{% url 'Instructor:homeInstructor' %}">Retour au planning</a>

</div>
{% endblock %}

Secretary/templates/planningInstructor.html
{% extends "base.html" %}
{% block title %}Edit{% endblock %}
{% block content %}
<div class="container-fluid">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}

    <div class="row justify-content-center mt-5">
        <div class="col-8">

            <h1>Planning de {{instructor.username}}</h1>
            <a href="{% url 'Secretary:addPlanningIns' instructor.id %}" class="btn btn-info">Ajouter un RDV</a>

            <table class="table table-bordered table-striped table-hover mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Heure</th>
                        <th scope="col">Instructor</th>
                        <th scope="col">Adresse</th>
                        <th scope="col">Modifier</th>
                        <th scope="col">Supprimer</th>

                    </tr>
                </thead>
                <tbody>
                    {% for plan in plannings %}
                    <tr>
                        <td>{{ plan.student.username }}</td>
                        <td>{{ plan.date|date:"d-m-Y" }}</td>
                        <td>{{ plan.date|date:"H:i" }}</td>
                        <td>{{ plan.place }}</td>
                        <td><a class="btn btn-warning" href="{% url 'Secretary:modifierPlanning' plan.id %}">Modifier</a></td>
                        <td><a class="btn btn-danger" href="{% url 'Secretary:confirmDeletePlanning' plan.id %}">Supprimer</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
<a class="btn btn-dark" href="{% url 'Secretary:homeSecretary'%}">Retour</a>

{% endblock %}
```

Secretary/templates/planningStudent.html
{% extends "base.html" %}
{% block title %}Edit{% endblock %}
{% block content %}
<div class="container-fluid">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}

    <div class="row justify-content-center mt-5">
        <div class="col-8">

            <h1>Planning de {{student.username}}</h1>
            <a href="{% url 'Secretary:addPlanning' student.id %}" class="btn btn-info">Ajouter un RDV</a>
            <a class="btn btn-dark" href="{% url 'Secretary:homeSecretary'%}">Retour</a>    

            <table class="table table-bordered table-striped table-hover mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Heure</th>
                        <th scope="col">Instructor</th>
                        <th scope="col">Adresse</th>
                        <th scope="col">Modifier</th>
                        <th scope="col">Supprimer</th>

                    </tr>
                </thead>
                <tbody>
                    {% for plan in plannings %}
                    <tr>
                        <td>{{ plan.date|date:"d-m-Y" }}</td>
                        <td>{{ plan.date|date:"H:i" }}</td>
                        <td>{{ plan.instructor.username }}</td>
                        <td>{{ plan.place }}</td>
                        <td><a class="btn btn-warning" href="{% url 'Secretary:modifierPlanning' plan.id %}">Modifier</a></td>
                        <td><a class="btn btn-danger" href="{% url 'Secretary:confirmDeletePlanning' plan.id %}">Supprimer</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock %}
```

Secretary/templates/studentList.html
{% extends "base.html" %}
{% block title %}Student{% endblock %}
{% block content %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
<div class="row justify-content-center mt-5">
    <div class="col-10">
        <h1>Driving School</h1>
        <h2>Students</h2>
        <a class="btn btn-primary" href="{% url 'Secretary:homeSecretary' %}">Back</a>
        <a class="btn btn-dark" href="{% url 'Secretary:addStudent' %}">Add a student</a>
        {% if student_list%}
        <table class="table table-bordered table-striped table-hover mt-4">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Nom d'utilisateur</th>
                    <th scope="col">Planning</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for student in student_list%}
                <tr>

                    <td><a class="btn btn-link" href="{% url 'Secretary:studentDetail' student.id %}">{{ student.username }}</a></td>
                    {% if student.planning_set.all %}
                    <td><a class="btn btn-dark" href="{% url 'Secretary:planningStudent' student.id %}">Voir le planning</a>
                    </td>
                    {% else %}
                    <td>
                        <a href="{% url 'Secretary:addPlanning' student.id %}" class="btn btn-info">Ajouter un RDV</a>
                    </td>
                    {% endif %}
                    <td class="d-flex">
                        <a class="btn btn-danger" href="{% url 'Secretary:confirmDeleteStudent' student.id %}">Supprimer</a>

                        <a href="{% url 'Secretary:editStudent' student.id %}"
                            class="btn btn-warning ml-2">Modifier</a>

                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}