DSchool/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = 'Driving School Administration'
admin.site.site_title = 'Driving School Administration'
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Student.urls')),
    path('instructor/', include('Instructor.urls')),
    path('secretary/', include('Secretary.urls')),  
    path('logout/', LogoutView.as_view(), name='logout'),
]

Instructor/urls.py
from django.urls import path
from . import views

app_name = 'Instructor'
urlpatterns =[
	path('homeInstructor/',views.homeInstructor, name='homeInstructor'),
    path('', views.loginInstructor, name='loginInstructor'),
    path('profileStudent/<int:student_id>/', views.profileStudent, name='studentProfile'),
    path('detailInstructor', views.detailInstructor, name='detailInstructor'),
    path('addPlanningInstructor/', views.addPlanningInstructor, name='addPlanningInstructor'),

    path('supprimer_planning/<int:planning_id>/', views.supprimer_planning, name='supprimer_planning'),
    path('confirmation_suppression/<int:planning_id>/', views.confirmer_suppression, name='confirmer_suppression'),
    path('instructor/planning/<int:planning_id>/modifier/', views.modifier_entry, name='modifier_entry'),
]

Student/urls.py
from django.urls import path
from . import views

app_name = 'Student'
urlpatterns =[
	path('homeStudent/',views.homeStudent, name='homeStudent'),
    path('', views.loginStudent, name='loginStudent'),
    path('detailStudent/',views.detailStudent, name='detailStudent'),
]

Student/models.py
from django.db import models

class Student(models.Model):
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    h_total = models.IntegerField(default=0)
    h_remaining = models.IntegerField(default=0)
    def __str__(self):
        return self.username

Student/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

Student/views.py
from django.shortcuts import render, redirect
from Secretary.models import Planning
from .forms import LoginForm
from .models import Student

def homeStudent(request):
    if "user_id" in request.session and request.session['user_role'] == 'student':
        context = {
            'plannings': Planning.objects.filter(student__id=request.session['user_id']).order_by('date'),
        }
        return render(request, 'homeStudent.html', context)
    else:
        return redirect('Student:loginStudent')
    
def detailStudent(request):
    context = {
        'student': Student.objects.get(pk=request.session['user_id']),
    }
    return render(request, 'detailStudent.html', context)

def loginStudent(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = Student.objects.filter(username=username, password=password).first()

            if user is not None:
                request.session['user_id'] = user.id
                request.session['user_role'] = 'student'
                return redirect('Student:homeStudent')
            else:
                return render(request, 'loginStudent.html', {'form': form, 'error_message': 'Invalid login'})

    else:
        form = LoginForm()

    return render(request, 'loginStudent.html', {'form': form})

Student/templates/detailStudent.html
{% extends "base.html" %}
{% block title %}Profil{% endblock %}
{% block content %}
<style>
    body {
        background: radial-gradient(circle at 18.7% 37.8%, rgb(255, 0, 0) 0%, rgb(225, 234, 238) 90%);
    }
    .navbar {
        background: radial-gradient(circle at 18.7% 37.8%, rgb(225, 234, 238) 0%, rgb(255, 0, 0) 90%);
    }
    .navlink {
        color: black;
    }
</style>
<div class="container-fluid">
    {% if student %}
    <div class="row justify-content-center mt-5">
        <div class="col-8">
            <h1>Détails de l'étudiant : {{ student.username }}</h1>
            <table class="table table-bordered table-striped table-hover mt-3">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Nom d'utilisateur</th>
                        <th scope="col">Total d'heures</th>
                        <th scope="col">Heures restantes</th>
                        <th scope="col">Planning</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ student.username }}</td>
                        <td>{{ student.h_total }}</td>
                        <td>{{ student.h_remaining }}</td>
                        <td><a class="btn btn-dark" href="{% url 'Student:homeStudent' %}">Voir votre planning</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

Student/templates/homeStudent.html
{% extends "base.html" %}
{% block content %}

<style>
    body {
        background: radial-gradient(circle at 18.7% 37.8%, rgb(255, 0, 0) 0%, rgb(225, 234, 238) 90%);
    }
    .navbar {
        background: radial-gradient(circle at 18.7% 37.8%, rgb(225, 234, 238) 0%, rgb(255, 0, 0) 90%);
    }
    .navlink {
        color: black;
    }
</style>
<div class="container-fluid">
    {% if plannings %}
    <div class="row justify-content-center mt-5">
        <div class="col-8">
            <h1>Votre planning</h1>
            <a class="btn btn-dark" href="{% url 'Student:detailStudent' %}">Profil</a>
            <table class="table table-bordered table-striped table-hover mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Heure</th>
                        <th scope="col">Instructor</th>
                        <th scope="col">Adresse</th>
                    </tr>
                </thead>
                <tbody>
                    {% for planning in plannings %}
                    <tr>
                        <td>{{ planning.date|date:"d-m-Y" }}</td>
                        <td>{{ planning.date|date:"H:i" }}</td>
                        <td>{{ planning.instructor.username }}</td>
                        <td>{{ planning.place }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <p> Vous n'avez pas encore de rendez-vous</p>
    {% endif %}
</div>
{% endblock %}

Student/templates/loginStudent.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Planning-all</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background: radial-gradient(circle at 18.7% 37.8%, rgb(255, 0, 0) 0%, rgb(225, 234, 238) 90%);
        }

        .custom-form {
            background: radial-gradient(circle at 18.7% 37.8%, rgb(225, 234, 238) 70%, rgb(255, 0, 0) 20%);
            border: 1px solid #ccc;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin-top: 50px;
            text-align: center;

        }

        h1 {
            color: #333;
        }

        form {
            width: 50%;
            margin: 0 auto;
        }

        input,
        label {
            margin-top: 1rem;
        }

        .btn-dark {
            background-color: #343a40;
            color: #fff;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-6">
                <div class="custom-form">
                    <h1>Welcome aboard, dear Student</h1>
                    <form method="post" role="form" action="{% url 'Student:loginStudent' %}">
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                        {% csrf_token %}
                        {{ form.username.label_tag }}
                        {{ form.username }}
                        {{ form.password.label_tag }}
                        {{ form.password }}
                        <input class="btn btn-dark" type="submit" value="Login" />
                    </form>
                    <a href="{% url 'Instructor:loginInstructor' %}">Référent ? Cliquez ici pour vous connecter</a>
                </div>
            </div>
        </div>
    </div>
</body>

</html>