DSchool/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = 'Driving School Administration'
admin.site.site_title = 'Driving School Administration'
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Student.urls')),
    path('instructor/', include('Instructor.urls')),
    path('secretary/', include('Secretary.urls')),  
    path('logout/', LogoutView.as_view(), name='logout'),
]

Instructor/urls.py
from django.urls import path
from . import views

app_name = 'Instructor'
urlpatterns =[
	path('homeInstructor/',views.homeInstructor, name='homeInstructor'),
    path('', views.loginInstructor, name='loginInstructor'),
    path('profileStudent/<int:student_id>/', views.profileStudent, name='studentProfile'),
    path('detailInstructor', views.detailInstructor, name='detailInstructor'),
    path('addPlanningInstructor/', views.addPlanningInstructor, name='addPlanningInstructor'),

    path('supprimer_planning/<int:planning_id>/', views.supprimer_planning, name='supprimer_planning'),
    path('confirmation_suppression/<int:planning_id>/', views.confirmer_suppression, name='confirmer_suppression'),
    path('instructor/planning/<int:planning_id>/modifier/', views.modifier_entry, name='modifier_entry'),
]

Student/urls.py
from django.urls import path
from . import views

app_name = 'Student'
urlpatterns =[
	path('homeStudent/',views.homeStudent, name='homeStudent'),
    path('', views.loginStudent, name='loginStudent'),
    path('detailStudent/',views.detailStudent, name='detailStudent'),
]

Instructor/models.py
from django.db import models

class Instructor(models.Model):
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    name = models.CharField(max_length=200,default="")
    lastname = models.CharField(max_length=200,default="")
    def __str__(self):
        return self.username

Instructor/forms.py
from django import forms
from Secretary.models import Planning

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class PlanningFormAdd(forms.ModelForm):
    class Meta:
        model = Planning
        fields = ["student", "date", "place"]
        date = forms.DateTimeField(
            widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            input_formats=['%Y-%m-%dT%H:%M'],
        )

class PlanningFormModif(forms.ModelForm):
    class Meta:
        model = Planning
        fields = [ "date", "place"]
        date = forms.DateTimeField(
            widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            input_formats=['%Y-%m-%dT%H:%M'],
        )        

Instructor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Instructor
from Secretary.models import Secretary, Planning
from Student.models import Student
from .forms import LoginForm, PlanningFormAdd, PlanningFormModif
from django.contrib import messages



def homeInstructor(request):
    if "user_id" in request.session and request.session['user_role'] == 'instructor':
        plannings = Planning.objects.filter(instructor__id=request.session['user_id']).order_by('date')
        context ={
            'plannings': plannings
        }
        return render(request, 'homeInstructor.html',context)

    else:
        return redirect('Instructor:loginInstructor')
    
    
def profileStudent(request, student_id):
    return render(request, 'studentProfile.html', {'student': Student.objects.get(pk=student_id)})

def detailInstructor(request):
    context = {
        'instructor': Instructor.objects.get(pk=request.session['user_id']),
    }
    return render(request, 'detailInstructor.html', context)

def addPlanningInstructor(request):
    if request.method == 'POST':
        form = PlanningFormAdd(request.POST)
        if form.is_valid():
            student = form.cleaned_data['student']
            instructor = Instructor.objects.get(pk=request.session['user_id'])
            form.instance.instructor = instructor
            if student.h_remaining > 0:
                student.h_remaining -= 1
                student.save()
                form.save()
                return redirect('Instructor:homeInstructor')
            else:
                messages.error(request, "Cet étudiant n'as plus de crédit")
                return redirect('Instructor:homeInstructor')
    else:
        form = PlanningFormAdd()
    
    return render(request, 'addPlanningInstructor.html', {'form': form}) 

def modifier_entry(request, planning_id):
    planning = get_object_or_404(Planning, pk=planning_id)
    form = PlanningFormModif(request.POST, instance=planning)
    if form.is_valid():
        instructor = Instructor.objects.get(pk=request.session['user_id'])
        form.instance.instructor = instructor
        form.instance.student = planning.student
        form.save()
        return redirect('Instructor:homeInstructor')
    else:
        form = PlanningFormModif(instance=planning)
    return render(request, 'modifier_entry.html', {'form': form, 'planning': planning })

def confirmer_suppression(request, planning_id):
    planning = get_object_or_404(Planning, pk=planning_id)
    return render(request, 'confirmer_suppression.html', {'planning': planning})

def supprimer_planning(request, planning_id):
    planning = get_object_or_404(Planning, pk=planning_id)
    if request.method == 'POST':
        planning.delete()
    return redirect('Instructor:homeInstructor')
    return render(request, 'supprimer_planning.html', {'planning': planning})
      

def loginInstructor(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = Instructor.objects.filter(username=username, password=password).first()
            role = 'instructor'
            if user == None:
                user = Secretary.objects.filter(username=username, password=password).first()
                role = 'secretary'

            if user is not None:
                request.session['user_id'] = user.id
                request.session['user_role'] = role
                if role == 'secretary':
                    return redirect('Secretary:homeSecretary')
                return redirect('Instructor:homeInstructor')
            else:
                return render(request, 'loginInstructor.html', {'form': form, 'error_message': 'Invalid login'})

    else:
        form = LoginForm()

    return render(request, 'loginInstructor.html', {'form': form})

Instructor/templates/addPlanningInstructor.html
{% extends "base.html" %}
{% block title %}Add{% endblock %}
{% block content %}
<style>
    body {
        background: radial-gradient(circle at 18.7% 37.8%, rgb(255, 0, 0) 0%, rgb(225, 234, 238) 90%);
    }
    .navbar {
        background: radial-gradient(circle at 18.7% 37.8%, rgb(225, 234, 238) 0%, rgb(255, 0, 0) 90%);
    }
    .navlink {
        color: black;
    }
</style>
    <form method="post">
        {% csrf_token %}
        {{ form.student }}
        {{ form.instructor }}
        <input type="datetime-local" name="{{ form.date.name }}" value="{{ form.date.value|default:'' }}" required>
        {{ form.place }}
        
        <button class="btn btn-primary" type="submit">Enregistrer</button>
    </form>
    <a class="btn btn-dark" href="{% url 'Instructor:homeInstructor' %}">Retour au planning</a>
    {% endblock %}

Instructor/templates/confirmer_suppression.html
{% extends "base.html" %}
{% block title %}Confirm{% endblock %}
{% block content %}
<div>
    <style>
        body {
            background: radial-gradient(circle at 18.7% 37.8%, rgb(255, 0, 0) 0%, rgb(225, 234, 238) 90%);
        }
        .navbar {
            background: radial-gradient(circle at 18.7% 37.8%, rgb(225, 234, 238) 0%, rgb(255, 0, 0) 90%);
        }
        .navlink {
            color: black;
        }
    </style>
<form method="post" action="{% url 'Instructor:supprimer_planning' planning.id %}">
    {% csrf_token %}
    <p>Êtes-vous sûr de vouloir supprimer le RDV avec  {{ planning.student }} le {{ planning.date|date:"d-m-Y" }} à {{ planning.date|date:"H:i" }} ?</p>
    <input class="btn btn-danger" type="submit" value="Confirmer la suppression">
</form>
    <a class="btn btn-dark" href="{% url 'Instructor:homeInstructor' %}">Retour au planning</a>
</div>
{% endblock %}

Instructor/templates/detailInstructor.html
{% extends "base.html" %}
{% block title %}Profil{% endblock %}
{% block content %}
<style>
       body {
           background: radial-gradient(circle at 18.7% 37.8%, rgb(255, 0, 0) 0%, rgb(225, 234, 238) 90%);
       }
       .navbar {
           background: radial-gradient(circle at 18.7% 37.8%, rgb(225, 234, 238) 0%, rgb(255, 0, 0) 90%);
       }
       .navlink {
           color: black;
       }
   </style>
<div>
       {% if instructor %}
              <table class="table table-bordered table-striped table-hover mt-4">
                     <thead class="thead-dark">
                       <tr>
                            <th>Username</th>
                            <th>Firstname</th>
                            <th>Lastname</th>
                       </tr>
                     </thead>
                       <tr>
                            <td>{{ instructor.username }}</td>
                            <td>{{ instructor.name }}</td>
                            <td>{{ instructor.lastname }}</td>
                       </tr>
              </table> 
       {% endif %}
                     
       <a class="btn btn-dark" href="{% url 'Instructor:homeInstructor' %}">Retour au planning</a>

</div>
{% endblock %}

Instructor/templates/homeInstructor.html
{% extends "base.html" %}
{% block content %}
<style>
  body {
      background: radial-gradient(circle at 18.7% 37.8%, rgb(255, 0, 0) 0%, rgb(225, 234, 238) 90%);
  }
  .navbar {
      background: radial-gradient(circle at 18.7% 37.8%, rgb(225, 234, 238) 0%, rgb(255, 0, 0) 90%);
  }
  .navlink {
      color: black;
  }
</style>
<div>
  {% if plannings %}
  <h1>Planning Instructor</h1>
  {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
  {% endif %}
    <table class="table table-bordered table-striped table-hover mt-4">
      <thead class="thead-dark">
        <tr>
          <th>Student</th>
          <th>Date</th>
          <th>Hour</th>
          <th>Place</th>
          <th>Modifier</th>
          <th>Supprimer</th>
        </tr>
        </thead>
    {% for planning in plannings %}
        <tr>
          <td><a class="btn btn-dark" href="{% url 'Instructor:studentProfile' planning.student.id %}">{{ planning.student }}</a></td>
          <td>{{ planning.date|date:"d-m-Y" }}</td>
          <td>{{ planning.date|date:"H:i" }}</td>
          <td>{{ planning.place }}</td>
          <td><a class="btn btn-warning" href="{% url 'Instructor:modifier_entry' planning.id %}">Modifier</a></td>
          <td><a class="btn btn-danger" href="{% url 'Instructor:confirmer_suppression' planning.id %}">Supprimer</a></td>
        </tr>
    {% endfor %}
      </table>
      {% else %}
      <p>Vous n'avez pas encore de rendez-vous</p>
      {% endif %}
    <a class="btn btn-primary" href="{% url 'Instructor:addPlanningInstructor' %}">Ajouter un RDV</a>
    <a class="btn btn-primary" href="{% url 'Instructor:detailInstructor' %}">Mon profil</a>  
</div>

{% endblock %}

Instructor/templates/loginInstructor.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Planning-all</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .custom-form {
            border: 1px solid #ccc;
            padding: 20px;
            margin-top: 50px;
            text-align: left;
        }

        form {
            width: 50%;
        }

        input,
        label {
            margin-top: 1rem;
        }

        body {
            background: radial-gradient(circle at 18.7% 37.8%, rgb(255, 0, 0) 0%, rgb(225, 234, 238) 90%);
        }

        .navbar {
            background: radial-gradient(circle at 18.7% 37.8%, rgb(225, 234, 238) 0%, rgb(255, 0, 0) 90%);
        }

        .navlink {
            color: black;
        }
    </style>
</head>

<body>

    <div class="container">
        <div class="row justify-content-center">

            <div class="col-6">

                <div class="custom-form mx-auto">
                    <h1>Welcome aboard Referent !</h1>

                    <form method="post" role="form" action="{% url 'Instructor:loginInstructor' %}">
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                        {% csrf_token %}
                        {{ form.username.label_tag }}
                        {{ form.username }}
                        {{ form.password.label_tag }}
                        {{ form.password }}
                        <input type="submit" value="Login" class="btn btn-dark" />
                    </form>
                    <a href="{% url 'Student:loginStudent' %}">Student ? Cliquez ici pour vous connecter</a>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

Instructor/templates/modifier_entry.html
{% extends "base.html" %}
{% block title %}Modifier{% endblock %}
{% block content %}
<style>
    body {
        background: radial-gradient(circle at 18.7% 37.8%, rgb(255, 0, 0) 0%, rgb(225, 234, 238) 90%);
    }
    .navbar {
        background: radial-gradient(circle at 18.7% 37.8%, rgb(225, 234, 238) 0%, rgb(255, 0, 0) 90%);
    }
    .navlink {
        color: black;
    }
</style>
<div>
<form method="post">
    {% if error_message %}<p>{{ error_message }}</p>{% endif %}
    {% csrf_token %}
    {{ form.student }}
    {{ form.date }}
    {{ form.place }}
    <input class="btn btn-primary" type="submit" value="Enregistrer les modifications">
</form>
    <a class="btn btn-dark" href="{% url 'Instructor:homeInstructor' %}">Retour au planning</a>

</div>
{% endblock %}

Instructor/templates/studentProfile.html
{% extends "base.html" %}
{% block title %}Profil Student{% endblock %}
{% block content %}
<style>
    body {
        background: radial-gradient(circle at 18.7% 37.8%, rgb(255, 0, 0) 0%, rgb(225, 234, 238) 90%);
    }
    .navbar {
        background: radial-gradient(circle at 18.7% 37.8%, rgb(225, 234, 238) 0%, rgb(255, 0, 0) 90%);
    }
    .navlink {
        color: black;
    }
</style>
<div>
    {% if student%}
    <table>
        <tr>
            <th>Username</th>
            <th>Total hour</th>
            <th>Hour remaining</th>
        </tr>
        <tr>
            <td>{{ student.username }}</td>
            <td>{{ student.h_total }}</td>
            <td>{{ student.h_remaining }}</td>
        </tr>
    </table>
    {% endif %}  
    <a class="btn btn-dark" href="{% url 'Instructor:homeInstructor' %}">Retour au planning</a>
</div> 
{% endblock %}
```